DROP TABLE RECEIVERS_USERS IF EXISTS;
DROP TABLE RECEIVER IF EXISTS;
DROP TABLE USERS IF EXISTS;

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RECEIVER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FISCAL_CODE VARCHAR(255) NOT NULL UNIQUE,
    ADDRESS VARCHAR(255),
    IS_VALID BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS RECEIVERS_USERS (
    RECEIVER_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (RECEIVER_ID, USER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES RECEIVER(id) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(id) ON DELETE CASCADE
);

INSERT INTO USERS (USERNAME)
VALUES ('user1');

INSERT INTO USERS (USERNAME)
VALUES ('user2');
