services:
  mongo:
    image: mongo:latest
    container_name: receivermanager-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminuser
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: receivers
    volumes:
      - mongo_data:/data/db
      - ./receivermanager-mongo-init-scripts:/docker-entrypoint-initdb.d:ro
volumes:
  mongo_data: