CREATE TABLE IF NOT EXISTS REQUEST_LOG (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  TRACEPARENT VARCHAR(255) NOT NULL,
  DELIVERY_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS REQUEST_LOG_DOCUMENTS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REQUEST_LOG_ID BIGINT NOT NULL,
  DOCUMENT VARCHAR(255) NOT NULL,
  FOREIGN KEY (REQUEST_LOG_ID) REFERENCES REQUEST_LOG(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REQUEST_LOG_RECEIVERS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REQUEST_LOG_ID BIGINT NOT NULL,
  RECEIVER VARCHAR(255) NOT NULL,
  FOREIGN KEY (REQUEST_LOG_ID) REFERENCES REQUEST_LOG(id) ON DELETE CASCADE
);
