CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  STATUS VARCHAR(50) NOT NULL,
  TRACEPARENT VARCHAR(255) NOT NULL,
  CONSTRAINT UNIQUE_STATUS_TRACEPARENT UNIQUE (STATUS, TRACEPARENT)
);
