CREATE TABLE IF NOT EXISTS DELIVERY (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  STATUS VARCHAR(25) NOT NULL,
  TRACEPARENT VARCHAR(255) UNIQUE,
  USERNAME VARCHAR(255),
  INSERT_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS TIMESTAMP
);
